name: Go Docker

on:
  push:
    paths:
      - 'extension/tgbot/**'
    branches: [ master ]
  pull_request:
    types:
      - closed

jobs:
  docker:
    name: Docker
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./extension/tgbot
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./extension/tgbot
          push: true
          platforms: linux/amd64,linux/arm64
          tags: iamthen0ise/w2r-tgbot:latest
