name: Go

on:
  push:
    paths:
      - 'extension/tgbot/**'
    branches: [ master ]
  pull_request:
    paths:
      - 'extension/tgbot/**'
    branches: [ master ]

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./extension/tgbot
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Get dependencies
        run: go mod download

      - name: Format
        run: test -z $(gofmt -l .)

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./extension/tgbot
          push: true
          tags: iamthen0ise/w2r-tgbot:latest
        if: github.ref == 'refs/heads/master'
        - name: Build
          run: go build -v ./...
