name: Go

on:
  push:
    paths:
      - 'extension/tgbot/**'
    branches: [ master ]
  pull_request:
    paths:
      - 'extension/tgbot/**'
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Check out code
      uses: actions/checkout@v2

    - name: Get dependencies
      run: go mod download
      working-directory: ./extension/tgbot

    - name: Build
      run: go build -v ./...
      working-directory: ./extension/tgbot

    - name: Test
      run: go test -v ./...
      working-directory: ./extension/tgbot

    - name: Format
      run: test -z $(gofmt -l .)
      working-directory: ./extension/tgbot

    - name: Lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: latest
        working-directory: ./extension/tgbot

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      if: github.ref == 'refs/heads/master'

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./extension/tgbot
        push: true
        tags: iamthen0ise/w2r-tgbot:latest
      if: github.ref == 'refs/heads/master'
