name: Webhook
on:
  repository_dispatch:
    types: [webhook]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
      
      - name: Add page
        run: ./scripts/new-page.sh --title "${{ github.event.client_payload.title }}" --url "${{ github.event.client_payload.url }}" --tags "${{ github.event.client_payload.tags }}"
      
      - name: Add & Commit
        uses: EndBug/add-and-commit@v7.3.0
        with:
          add: 'content/items'
          author_name: snegovik-bot
          author_email: snegovik@tg.me
          committer_name: snegovik-bot
          commiter_email: snegovik@tg.me
          message: 'Add ${{ github.event.client_payload.title }}'
          
