name: Webhook
on:
  repository_dispatch:
    types: [webhook]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
      
      - name: Add page
        run: ./scripts/new-page.sh ${{ github.event.client_payload.title }} ${{ github.event.client_payload.url }} ${{ github.event.client_payload.tags }}
      
      - name: Move file
        run: ls -lah .
      # - name: Add & Commit
      #   uses: EndBug/add-and-commit@v7.0.0        
